---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-bedrock
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minecraft-community
  namespace: minecraft
spec:
  interval: 1m
  url: https://itzg.github.io/minecraft-server-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  interval: 1m
  chart:
    spec:
      chart: minecraft
      version: '2.1.5'
      sourceRef:
        kind: HelmRepository
        name: minecraft-community
        namespace: minecraft
      interval: 1m
  values:
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      gameMode: "creative"
      whitelist: "869844ea-ff4c-47df-9275-54ebb5ed3cc2"
      ops: "869844ea-ff4c-47df-9275-54ebb5ed3cc2"
      cheats: true
      serverName: "Monty"
    persistence:
      dataDir:
        enabled: true