---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-bedrock
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minecraft-community
  namespace: minecraft-bedrock
spec:
  interval: 1m
  url: https://itzg.github.io/minecraft-server-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-bedrock
  namespace: minecraft-bedrock
spec:
  interval: 1m
  chart:
    spec:
      chart: minecraft-bedrock
      version: '1.2.0'
      sourceRef:
        kind: HelmRepository
        name: minecraft-community
        namespace: minecraft-bedrock
      interval: 1m
  values:
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      gameMode: "creative"
      whitelist: "000901F73A7038A0"
      ops: "000901F73A7038A0"
      cheats: true
      serverName: "Monty"
      serviceType: LoadBalancer
    persistence:
      dataDir:
        enabled: true