name: AWSK3S01 Pre-flight checks
on:
  pull_request:
    paths:
      - "terraform/awsk3s01/**"
  workflow_dispatch:
jobs:
  check:
    name: Pull Request pre-flight checks
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        folder:
          - terraform/awsk3s01
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pull_request
        with:
          path: ${{ matrix.folder }}
          github_token: ${{ secrets.GITHUB_TOKEN }}