name: AWSK3S01 Trunk Apply
on:
  push:
    branches:
      - "trunk"
    paths:
      - "terraform/awsk3s01/**"
jobs:
  apply:
    name: Apply Terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        folder:
          - terraform/awsk3s01
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/apply
        with:
          path: ${{ matrix.folder }}
          auto_apply: "false"
