name: VPC Deployment
on:
  pull_request:
    paths:
      - "terraform/vpc/**"
  workflow_dispatch:
jobs:
  check:
    name: Pull Request pre-flight checks
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        folder:
          - terraform/vpc/us-east-2
    steps:
      - uses: ./.github/actions/pull_request
        with:
          path: ${{ matrix.folder }}
          github_token: ${{ secrets.GITHUB_TOKEN }}