name: VPC Trunk Apply (force)
on:
  workflow_dispatch:
    inputs:
      for_real:
        description: "Should the workflow apply or just plan?"
        required: true
        default: "plan"
jobs:
  apply:
    name: Apply Terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        folder:
          - terraform/vpc/us-east-2
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pull_request
        if: ${{ github.event.inputs.for_real == 'plan' }}
        with:
          path: ${{ matrix.folder }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/apply
        if: ${{ github.event.inputs.for_real == 'apply' }}
        with:
          path: ${{ matrix.folder }}
          auto_approve: true

